blank_issues_enabled: false
contact_links:
  - name: Feature requests and ideas
    url: https://github.com/davidmc24/gradle-avro-plugin/discussions/categories/ideas
    about: Suggest an idea for this project.
  - name: Questions
    url: https://github.com/davidmc24/gradle-avro-plugin/discussions/categories/q-a
    about: Please ask and answer questions here.
