#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

baseURL = "/"
title = "Apache Avro"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"] 

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"] 

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"] 


# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages.params]
[languages.en.params]
title = "Apache Avro"
description = ""
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print", "RSS"]

[params]
avroversion = "++version++"
copyright = "The Apache Software Foundation"
apache_foundation = "https://www.apache.org/"
apache_events_logo = "https://www.apache.org/events/current-event-234x60.png"
apache_events_url = "https://www.apache.org/events/current-event.html"
privacy_policy = "http://www.apache.org/foundation/policies/privacy.html"
license = "http://www.apache.org/licenses/"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "++version++"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://avro.apache.org"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/apache/avro"
github_subdir = "doc"

# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/apache/avro"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
# github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "d72aa9b2712488cc3"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = true
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
sidebar_menu_foldable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[params.asf]
[[params.asf.links]]
name = "ASF Web Site"
url = "http://www.apache.org/"

[[params.asf.links]]
name = "License"
url = "http://www.apache.org/licenses/"

[[params.asf.links]]
name = "Donate"
url = "http://www.apache.org/foundation/sponsorship.html"


[[params.asf.links]]
name = "Thanks"
url = "http://www.apache.org/foundation/thanks.html"

[[params.asf.links]]
name = "Security"
url = "http://www.apache.org/security/"


[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
  name = "User mailing list"
  url = "https://lists.apache.org/list.html?user@avro.apache.org"
  icon = "fa fa-envelope"
  desc = "Discussion and help from your fellow users"
[[params.links.user]]
  name ="Twitter"
  url = "https://twitter.com/ApacheAvro"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
  name = "Stack Overflow"
  url = "https://stackoverflow.com/questions/tagged/avro"
  icon = "fab fa-stack-overflow"
  desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/apache/avro"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Issues"
  url = "https://issues.apache.org/jira/projects/AVRO/issues"
  icon = "fab fa-jira"
  desc = "Track bugs and new features"
[[params.links.developer]]
  name = "Chat with other project developers at Slack"
  url = "https://the-asf.slack.com/"
  icon = "fab fa-slack"
  desc = "Chat with other project developers at #avro channel"
[[params.links.developer]]
  name = "Developer mailing list"
  url = "https://lists.apache.org/list.html?dev@avro.apache.org"
  icon = "fa fa-envelope"
  desc = "Discuss development issues around the project"

[[params.versions]]
  version = "++version++ (Current)"
  url = "/docs/++version++/"

[[params.versions]]
version = "1.11.2"
url = "https://avro.apache.org/docs/1.11.2/"

[[params.versions]]
version = "1.11.1"
url = "https://avro.apache.org/docs/1.11.1/"

[[params.versions]]
version = "1.11.0"
url = "https://avro.apache.org/docs/1.11.0/"

[[params.versions]]
  version = "1.10.2"
  url = "https://avro.apache.org/docs/1.10.2/"

[[params.versions]]
  version = "1.10.1"
  url = "https://avro.apache.org/docs/1.10.1/"

[[params.versions]]
  version = "1.10.0"
  url = "https://avro.apache.org/docs/1.10.0/"

[[params.versions]]
  version = "1.9.2"
  url = "https://avro.apache.org/docs/1.9.2/"

[[params.versions]]
  version = "1.9.1"
  url = "https://avro.apache.org/docs/1.9.1/"

[[params.versions]]
  version = "1.9.0"
  url = "https://avro.apache.org/docs/1.9.0/"

[[params.versions]]
  version = "1.8.2"
  url = "https://avro.apache.org/docs/1.8.2/"

[[params.versions]]
  version = "1.8.1"
  url = "https://avro.apache.org/docs/1.8.1/"

[[params.versions]]
  version = "1.8.0"
  url = "https://avro.apache.org/docs/1.8.0/"

[[params.versions]]
  version = "1.7.7"
  url = "https://avro.apache.org/docs/1.7.7/"

[[params.versions]]
  version = "1.7.6"
  url = "https://avro.apache.org/docs/1.7.6/"

[[params.versions]]
  version = "1.7.5"
  url = "https://avro.apache.org/docs/1.7.5/"

[[params.versions]]
  version = "1.7.4"
  url = "https://avro.apache.org/docs/1.7.4/"

[[params.versions]]
  version = "1.7.3"
  url = "https://avro.apache.org/docs/1.7.3/"

[[params.versions]]
  version = "1.7.2"
  url = "https://avro.apache.org/docs/1.7.2/"

[[params.versions]]
  version = "1.7.1"
  url = "https://avro.apache.org/docs/1.7.1/"
  
[[params.versions]]
  version = "1.7.0"
  url = "https://avro.apache.org/docs/1.7.0/"
  
[[params.versions]]
  version = "1.6.3"
  url = "https://avro.apache.org/docs/1.6.3/"
  
[[params.versions]]
  version = "1.6.2"
  url = "https://avro.apache.org/docs/1.6.2/"
  
[[params.versions]]
  version = "1.6.1"
  url = "https://avro.apache.org/docs/1.6.1/"
  
[[params.versions]]
  version = "1.6.0"
  url = "https://avro.apache.org/docs/1.6.0/"
  
[[params.versions]]
  version = "1.5.4"
  url = "https://avro.apache.org/docs/1.5.4/"
  
[[params.versions]]
  version = "1.5.3"
  url = "https://avro.apache.org/docs/1.5.3/"
  
[[params.versions]]
  version = "1.5.2"
  url = "https://avro.apache.org/docs/1.5.2/"
  
[[params.versions]]
  version = "1.5.1"
  url = "https://avro.apache.org/docs/1.5.1/"
  
[[params.versions]]
  version = "1.5.0"
  url = "https://avro.apache.org/docs/1.5.0/"
  
[[params.versions]]
  version = "1.4.1"
  url = "https://avro.apache.org/docs/1.4.1/"
  
[[params.versions]]
  version = "1.4.0"
  url = "https://avro.apache.org/docs/1.4.0/"
  
[[params.versions]]
  version = "1.3.3"
  url = "https://avro.apache.org/docs/1.3.3/"
  
[[params.versions]]
  version = "1.3.2"
  url = "https://avro.apache.org/docs/1.3.2/"
  
[[params.versions]]
  version = "1.3.1"
  url = "https://avro.apache.org/docs/1.3.1/"
  
[[params.versions]]
  version = "1.3.0"
  url = "https://avro.apache.org/docs/1.3.0/"
  
[[params.versions]]
  version = "1.2.0"
  url = "https://avro.apache.org/docs/1.2.0/"
  
[[params.versions]]
  version = "1.1.0"
  url = "https://avro.apache.org/docs/1.1.0/"
  
[[params.versions]]
  version = "1.0.0"
  url = "https://avro.apache.org/docs/1.0.0/"
  
