name: Avro Compatibility Tests
on: [push, pull_request]
jobs:
  test:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0", "1.11.1"]
        gradle: ["5.1", "7.3"]
        java: ["8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
