name: Avro Compatibility Tests
on: [push, pull_request]
jobs:
  test:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["5.1", "6.8.3"]
        java: ["8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
