name: CI Build
on: [push, pull_request]
jobs:
  build:
    name: Baseline build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8.0.222
        architecture: x64
    - name: Output Java version
      run: java -version
    - name: Output Gradle version
      run: ./gradlew --version
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
    - name: Build with Gradle
      run: ./gradlew build --info
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
  compatibility-tests:
    name: Java ${{ matrix.java }}/${{ matrix.os }} compatibility
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [8, 11, 13, 14]
      fail-fast: true
      max-parallel: 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Output Java version
      run: java -version
    - name: Output Gradle version
      run: ./gradlew --version
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
    - name: Run version compatibility tests
      run: ./gradlew testVersionCompatibility --info
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
  unsupported-java-versions:
    name: Java ${{ matrix.java }}/${{ matrix.os }} compatibility
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [15-ea]
      fail-fast: false
      max-parallel: 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Output Java version
      run: java -version
    - name: Output Gradle version
      run: ./gradlew --version
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
    - name: Run tests
      continue-on-error: true
      run: ./gradlew build testVersionCompatibility --info
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
