name: Gradle Compatibility Tests
on: [push, pull_request]
jobs:
  test:
    name: "Compatibility: gradle ${{ matrix.gradle }}/java ${{ matrix.java }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: [
          "5.1", "5.1.1", "5.2", "5.2.1", "5.3", "5.3.1", "5.4", "5.4.1", "5.5", "5.5.1", "5.6", "5.6.1", "5.6.2", "5.6.3", "5.6.4",
          "6.0", "6.0.1", "6.1", "6.1.1", "6.2", "6.2.1", "6.2.2",
          "6.3", "6.4", "6.4.1", "6.5", "6.5.1", "6.6", "6.6.1",
          "6.7", "6.7.1", "6.8", "6.8.1", "6.8.2", "6.8.3", "6.9", "6.9.1",
          "7.0", "7.0.1", "7.0.2", "7.1", "7.1.1", "7.2"
          # See here for latest versions: https://services.gradle.org/versions/
        ]
        java: ["8", "11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
