# See https://docs.gradle.org/current/userguide/compatibility.html
name: Java Compatibility Tests
on: [push, pull_request]
jobs:
  java8-12:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"]
        gradle: ["5.1", "6.8.3"]
        java: ["8", "9", "10", "11", "12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  java13:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"]
        gradle: ["6.0", "6.8.3"]
        java: ["13"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  java14:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"]
        gradle: ["6.3", "6.8.3"]
        java: ["14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  java15:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"]
        gradle: ["6.7", "6.8.3"]
        java: ["15"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  java16:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"]
        gradle: ["7.2"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["16"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  java-ea:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"]
        gradle: ["7.2"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["17", "18-ea"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        continue-on-error: true
        with:
          arguments: --no-daemon --info --stacktrace testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
