name: Kotlin Plugin Compatibility Tests
on: [push, pull_request]
jobs:
  java8-gradle5_1:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}/java ${{ matrix.java }}//kotlin ${{ matrix.kotlin }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.0"] # Minimum version that this plugin supports
        gradle: ["5.1"] # Minimum version that this plugin supports
        java: ["8"] # Minimum version that this plugin supports
        kotlin: [
            "1.2.20", "1.2.21", # These don't support Java 10+
            "1.2.30", "1.2.31", "1.2.40", "1.2.41", "1.2.50", "1.2.51", "1.2.60", "1.2.61", "1.2.70", "1.2.71",
            "1.3.0", "1.3.10", "1.3.11",
            "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72"
            # Later versions require Gradle 5.3+
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testKotlinPluginCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }} -PkotlinPluginVersion=${{ matrix.kotlin }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  java8-gradle5_3:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}/java ${{ matrix.java }}//kotlin ${{ matrix.kotlin }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.0"] # Minimum version that this plugin supports
        gradle: ["5.3"] # Minimum version supported by these versions of the Kotlin plugin
        java: ["8"] # Minimum version that this plugin supports
        kotlin: [
            # These versions require Gradle 5.3+
            "1.4.0", "1.4.10", "1.4.20", "1.4.21", "1.4.30", "1.4.31", "1.4.32"
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testKotlinPluginCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }} -PkotlinPluginVersion=${{ matrix.kotlin }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  java11-gradle5_6_4:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}/java ${{ matrix.java }}//kotlin ${{ matrix.kotlin }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"] # Latest version that this plugin supports
        gradle: ["6.8.3"] # Latest version that this plugin supports
        java: ["11"] # Latest LTS version that this plugin supports
        kotlin: [
            # Earlier versions don't support Java 10+
            # These versions don't support Gradle 6+
            "1.2.30", "1.2.31", "1.2.40", "1.2.41", "1.2.50", "1.2.51", "1.2.60", "1.2.61", "1.2.70", "1.2.71",
            "1.3.0", "1.3.10", "1.3.11",
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testKotlinPluginCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }} -PkotlinPluginVersion=${{ matrix.kotlin }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

  modern:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}/java ${{ matrix.java }}//kotlin ${{ matrix.kotlin }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.10.2"] # Latest version that this plugin supports
        gradle: ["6.8.3"] # Latest version that this plugin supports
        java: ["11"] # Latest LTS version that this plugin supports
        kotlin: [
            # Earlier versions lack support for either Java 10+ or Gradle 6+
            "1.3.20", "1.3.21", "1.3.30", "1.3.31", "1.3.40", "1.3.41", "1.3.50", "1.3.60", "1.3.61", "1.3.70", "1.3.71", "1.3.72",
            "1.4.0", "1.4.10", "1.4.20", "1.4.21", "1.4.30", "1.4.31", "1.4.32"
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon --info --stacktrace testKotlinPluginCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }} -PkotlinPluginVersion=${{ matrix.kotlin }}
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
