# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Test Ruby'
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - .github/workflows/test-lang-ruby.yml
    - lang/ruby/**

defaults:
  run:
    working-directory: lang/ruby

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run: sudo apt-get install -qqy libsnappy-dev

      - uses: actions/cache@v3
        with:
          path: .gem
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Configure Bundler to Use Cache
        run: bundle config path .gem

      - name: Lint
        run: |
          PATH=$PWD/.gem/bin:$PATH
          ./build.sh lint

      - name: Test
        run: |
          PATH=$PWD/.gem/bin:$PATH
          ./build.sh test

  interop:
    name: Ruby ${{ matrix.ruby }} Interop
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run: sudo apt-get install -qqy libsnappy-dev

      - uses: actions/cache@v3
        with:
          path: .gem
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Configure Bundler to Use Cache
        run: bundle config path .gem

      - name: Cache Local Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Java Avro for Interop Test
        working-directory: .
        run: mvn -B install -DskipTests

      - name: Create Interop Data Directory
        working-directory: .
        run: mkdir -p build/interop/data

      - name: Generate Interop Resources
        working-directory: lang/java/avro
        run: mvn -B -P interop-data-generate generate-resources

      - name: Bundle Install
        run: |
          export GEM_HOME="$PWD/.gem/"
          export PATH="$GEM_HOME/bin:$PATH"
          bundle install

      - name: Generate Interop Data
        run: |
          export GEM_HOME="$PWD/.gem/"
          export PATH="$GEM_HOME/bin:$PATH"
          bundle exec rake --trace generate_interop

      - name: Run Interop Tests
        run: |
          export GEM_HOME="$PWD/.gem/"
          export PATH="$GEM_HOME/bin:$PATH"
          bundle exec rake --trace interop
